Repository Bit-Final-Project/moeego_server, pull requests merged in 2024-12, with the labels that each got.

#68 [BE] Ref: 댓글 조회 응답 예외처리 #67
  src/main/java/com/ncp/moeego/comment/controller/CommentController.java
Labels: ref

#71 [BE] Feat: 댓글 반환시 elapsedTime 추가
  src/main/java/com/ncp/moeego/article/service/ArticleServiceImpl.java
  src/main/java/com/ncp/moeego/comment/dto/CommentRequest.java
  src/main/java/com/ncp/moeego/comment/dto/CommentResponse.java
  src/main/java/com/ncp/moeego/comment/dto/MemberCommentResponse.java
  src/main/java/com/ncp/moeego/comment/entity/Comment.java
  src/main/java/com/ncp/moeego/comment/entity/CommentStatus.java
  src/main/java/com/ncp/moeego/comment/mapper/CommentMapper.java
  src/main/java/com/ncp/moeego/comment/repository/CommentRepository.java
  src/main/java/com/ncp/moeego/comment/service/CommentServiceImpl.java
  src/main/java/com/ncp/moeego/common/Date.java
  src/test/java/com/ncp/moeego/comment/test/CommentServiceTest.java
Labels: ref

#74 [BE] Ref: 댓글 쿼리 성능 향상
  src/main/java/com/ncp/moeego/comment/entity/Comment.java
  src/main/java/com/ncp/moeego/comment/repository/CommentRepository.java
  src/main/java/com/ncp/moeego/comment/service/CommentServiceImpl.java
Labels: ref

#77 [BE] Ref: OAuth2 로그인 세부사항 수정
  src/main/java/com/ncp/moeego/member/bean/JoinDTO.java
  src/main/java/com/ncp/moeego/member/bean/oauth2/NaverResponse.java
  src/main/java/com/ncp/moeego/member/bean/oauth2/OAuth2Response.java
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ncp/moeego/member/service/oauth2/OAuth2MemberService.java
Labels: ref

#91 [BE] Ref: Pro 엔티티 수정
  src/main/java/com/ncp/moeego/pro/bean/Pro.java
  src/main/java/com/ncp/moeego/pro/dto/ProApplyRequest.java
  src/main/java/com/ncp/moeego/pro/dto/ProJoinRequest.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: ref

#94 [BE] Fix: 컨트롤러 수정
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
Labels: fix

#95 [BE] Fix: 컨트롤러 수정
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
Labels: fix

#100 [BE] Feat: 찜한 달인 기능 구현
  src/main/java/com/ncp/moeego/article/controller/ArticleController.java
  src/main/java/com/ncp/moeego/article/service/ArticleServiceImpl.java
  src/main/java/com/ncp/moeego/comment/repository/CommentRepository.java
  src/main/java/com/ncp/moeego/favorite/bean/Favorite.java
  src/main/java/com/ncp/moeego/favorite/entity/Favorite.java
  src/main/java/com/ncp/moeego/favorite/repository/FavoriteRepository.java
  src/main/java/com/ncp/moeego/image/bean/Image.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/dto/FavoriteResponse.java
  src/main/java/com/ncp/moeego/pro/entity/Pro.java
  src/main/java/com/ncp/moeego/pro/entity/ProArticle.java
  src/main/java/com/ncp/moeego/pro/entity/Reserve.java
  src/main/java/com/ncp/moeego/pro/entity/ReserveTime.java
  src/main/java/com/ncp/moeego/pro/entity/Review.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#101 [BE] Feat: 찜한 달인 기능 구현
  src/main/java/com/ncp/moeego/favorite/repository/FavoriteRepository.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/dto/FavoriteDeleteRequest.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#122 [BE] Feat: 비밀번호 체크 및 회원 탈퇴 기능 구현
  build.gradle
  src/main/java/com/ncp/moeego/cancel/entity/Cancel.java
  src/main/java/com/ncp/moeego/cancel/repository/CancelRepository.java
  src/main/java/com/ncp/moeego/member/bean/SignOutDTO.java
  src/main/java/com/ncp/moeego/member/config/SecurityConfig.java
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/jwt/JWTFilter.java
  src/main/java/com/ncp/moeego/member/jwt/JWTUtil.java
  src/main/java/com/ncp/moeego/member/repository/MemberRepository.java
  src/main/java/com/ncp/moeego/member/service/CustomUserDetailsService.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/member/service/impl/AdminServiceImpl.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberInfoProviderImpl.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ncp/moeego/member/service/oauth2/OAuth2MemberService.java
Labels: feat

#127 [BE] Ref: 회원탈퇴 응답 수정
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
Labels: ref

#134 [BE] Feat: 회원정보 이름 수정 API 구현
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
Labels: feat

#138 [BE] Feat: 이메일 인증 API 구현
  build.gradle
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/service/impl/MailServiceImpl.java
Labels: feat

#141 [BE] Fix: 회원 정보 이름 오류 수정
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/jwt/JWTFilter.java
Labels: fix

#145 [BE] Ref: DB구조 추가 변경
  src/main/java/com/ncp/moeego/image/bean/Image.java
  src/main/java/com/ncp/moeego/member/controller/AdminController.java
  src/main/java/com/ncp/moeego/member/repository/MemberRepository.java
  src/main/java/com/ncp/moeego/member/service/AdminService.java
  src/main/java/com/ncp/moeego/member/service/impl/AdminServiceImpl.java
  src/main/java/com/ncp/moeego/pro/dto/FavoriteResponse.java
  src/main/java/com/ncp/moeego/pro/entity/Pro.java
  src/main/java/com/ncp/moeego/pro/entity/Review.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
Labels: ref

#148 [BE] Fix: JWT 이슈 해결
  src/main/java/com/ncp/moeego/member/config/SecurityConfig.java
  src/main/java/com/ncp/moeego/member/jwt/JWTFilter.java
  src/main/java/com/ncp/moeego/member/oauth2/CustomFormSuccessHandler.java
Labels: fix

#150 [BE] Fix: Mail 인증 체크 Post요청 처리
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
Labels: fix

#149 [BE] Feat: 달인 서비스 페이지 입력 및 출력 구현
  build.gradle
  src/main/java/com/ncp/moeego/exception/GlobalExceptionHandler.java
  src/main/java/com/ncp/moeego/image/bean/Image.java
  src/main/java/com/ncp/moeego/image/bean/ImageDTO.java
  src/main/java/com/ncp/moeego/image/service/ImageServiceImpl.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/dto/ItemResponse.java
  src/main/java/com/ncp/moeego/pro/dto/PostItemRequest.java
  src/main/java/com/ncp/moeego/pro/entity/Pro.java
  src/main/java/com/ncp/moeego/pro/entity/ProItem.java
  src/main/java/com/ncp/moeego/pro/entity/Reserve.java
  src/main/java/com/ncp/moeego/pro/entity/ReserveTime.java
  src/main/java/com/ncp/moeego/pro/entity/Review.java
  src/main/java/com/ncp/moeego/pro/repository/ProItemRepository.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/repository/ProServiceItemRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#156 [BE] Ref: 전체 엔티티 구조 변경
  src/main/java/com/ncp/moeego/article/entity/Article.java
  src/main/java/com/ncp/moeego/article/repository/ArticleRepository.java
  src/main/java/com/ncp/moeego/article/service/ArticleService.java
  src/main/java/com/ncp/moeego/article/service/ArticleServiceImpl.java
  src/main/java/com/ncp/moeego/cancel/entity/Cancel.java
  src/main/java/com/ncp/moeego/category/bean/MainCategory.java
  src/main/java/com/ncp/moeego/category/bean/MainCategoryDTO.java
  src/main/java/com/ncp/moeego/category/bean/SubCategory.java
  src/main/java/com/ncp/moeego/category/bean/SubCategoryDTO.java
  src/main/java/com/ncp/moeego/category/controller/MainCategoryController.java
  src/main/java/com/ncp/moeego/category/controller/SubCategoryController.java
  src/main/java/com/ncp/moeego/category/entity/MainCategory.java
  src/main/java/com/ncp/moeego/category/entity/SubCategory.java
  src/main/java/com/ncp/moeego/category/repository/MainCategoryRepository.java
  src/main/java/com/ncp/moeego/category/repository/SubCategoryRepository.java
  src/main/java/com/ncp/moeego/category/service/MainCategoryServiceImpl.java
  src/main/java/com/ncp/moeego/category/service/SubCategoryService.java
  src/main/java/com/ncp/moeego/category/service/SubCategoryServiceImpl.java
  src/main/java/com/ncp/moeego/comment/dto/CommentRequest.java
  src/main/java/com/ncp/moeego/comment/entity/Comment.java
  src/main/java/com/ncp/moeego/comment/mapper/CommentMapper.java
  src/main/java/com/ncp/moeego/comment/repository/CommentRepository.java
  src/main/java/com/ncp/moeego/comment/service/CommentService.java
  src/main/java/com/ncp/moeego/comment/service/CommentServiceImpl.java
  src/main/java/com/ncp/moeego/favorite/entity/Favorite.java
  src/main/java/com/ncp/moeego/favorite/repository/FavoriteRepository.java
  src/main/java/com/ncp/moeego/image/controller/ImageController.java
  src/main/java/com/ncp/moeego/image/entity/Image.java
  src/main/java/com/ncp/moeego/image/repository/ImageRepository.java
  src/main/java/com/ncp/moeego/image/service/ImageServiceImpl.java
  src/main/java/com/ncp/moeego/map/entity/Map.java
  src/main/java/com/ncp/moeego/member/entity/Member.java
  src/main/java/com/ncp/moeego/member/repository/MemberRepository.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ncp/moeego/pro/entity/Pro.java
  src/main/java/com/ncp/moeego/pro/entity/ProItem.java
  src/main/java/com/ncp/moeego/pro/entity/Review.java
  src/main/java/com/ncp/moeego/pro/repository/ProItemRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
  src/test/java/com/ncp/moeego/article/test/ArticleTest.java
Labels: ref

#160 [BE] Fix: Entity 및 DB 수정 후 소셜로그인 오류 해결
  src/main/java/com/ncp/moeego/member/oauth2/CustomFormSuccessHandler.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ncp/moeego/member/service/oauth2/OAuth2MemberService.java
Labels: fix

#162 [BE] Ref: Front 요구사항 - email 인증번호 log 출력 수정 완료
  src/main/java/com/ncp/moeego/member/service/impl/MailServiceImpl.java
Labels: ref

#164 [BE] Feat: 달인 서비스 등록시 초기값 반환
  src/main/java/com/ncp/moeego/category/entity/SubCategory.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/dto/InitItemResponse.java
  src/main/java/com/ncp/moeego/pro/dto/PostItemRequest.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#174 [BE] Feat: 회원 정보 수정 - 비밀번호, 휴대폰번호, 주소
  src/main/java/com/ncp/moeego/member/controller/MemberController.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
Labels: feat

#181 [BE] Feat: 달인 서비스 필터링+페이징 구현
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#188 [BE] Ref: Pro,ProItem,Review 엔티티 변경
  src/main/java/com/ncp/moeego/pro/entity/Pro.java
  src/main/java/com/ncp/moeego/pro/entity/ProItem.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
  src/main/java/com/ncp/moeego/review/bean/ReviewDTO.java
  src/main/java/com/ncp/moeego/review/controller/ReviewController.java
  src/main/java/com/ncp/moeego/review/entity/Review.java
  src/main/java/com/ncp/moeego/review/service/ReviewServiceImpl.java
Labels: ref

#201 [BE] Feat: 예약 기능 구현
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
  src/main/java/com/ncp/moeego/reservation/controller/ReservationController.java
  src/main/java/com/ncp/moeego/reservation/dto/ReservationRequest.java
  src/main/java/com/ncp/moeego/reservation/entity/Reservation.java
  src/main/java/com/ncp/moeego/reservation/entity/ReservationTime.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationRepository.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationService.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationServiceImpl.java
Labels: feat

#203 [BE] Feat: 예약 기능 예외처리
  src/main/java/com/ncp/moeego/image/repository/ImageRepository.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/reservation/controller/ReservationController.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationService.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationServiceImpl.java
  src/main/java/com/ncp/moeego/review/service/ReviewService.java
  src/main/java/com/ncp/moeego/review/service/ReviewServiceImpl.java
Labels: feat

#205 [BE] Feat: getExistingDateTime 구현
  src/main/java/com/ncp/moeego/reservation/controller/ReservationController.java
  src/main/java/com/ncp/moeego/reservation/dto/ExistingDateTimeResponse.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationService.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationServiceImpl.java
Labels: feat

#208 [BE] Fix: ReservationRequest dto클래스 수정
  build.gradle
  src/main/java/com/ncp/moeego/reservation/dto/ReservationRequest.java
Labels: fix

#220 [BE] Ref: 달인 찾기 기능 구현
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/repository/ProRepository.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#221 [BE] Feat: 예약내역 출력 로직 완성
  src/main/java/com/ncp/moeego/category/service/SubCategoryService.java
  src/main/java/com/ncp/moeego/favorite/repository/FavoriteRepository.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/dto/FavoritePostRequest.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
  src/main/java/com/ncp/moeego/reservation/controller/ReservationController.java
  src/main/java/com/ncp/moeego/reservation/dto/MyReservationResponse.java
  src/main/java/com/ncp/moeego/reservation/dto/ReceivedReservationResponse.java
  src/main/java/com/ncp/moeego/reservation/entity/ReservationTime.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationRepository.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationService.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationServiceImpl.java
Labels: feat

#241 [BE] Ref: 예약가능 시간대 조회 기능 수정
  src/main/java/com/ncp/moeego/reservation/controller/ReservationController.java
  src/main/java/com/ncp/moeego/reservation/dto/ExistingDateTimeResponse.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationRepository.java
  src/main/java/com/ncp/moeego/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationService.java
  src/main/java/com/ncp/moeego/reservation/service/ReservationServiceImpl.java
Labels: ref

#245 [BE] Feat: 달인 소개 수정 기능 구현
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#247 [BE] Feat: 달인 신청 기능 추가 및 달인 소개 수정
  src/main/java/com/ncp/moeego/pro/controller/ProController.java
  src/main/java/com/ncp/moeego/pro/service/ProService.java
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: feat

#251 [BE] Feat: 카테고리별 달인 인원 수 체크
  src/main/java/com/ncp/moeego/main/controller/AboutController.java
  src/main/java/com/ncp/moeego/member/bean/ProCountDTO.java
  src/main/java/com/ncp/moeego/member/repository/MemberRepository.java
  src/main/java/com/ncp/moeego/member/service/MemberService.java
  src/main/java/com/ncp/moeego/member/service/impl/MemberServiceImpl.java
Labels: feat

#254 [BE] Ref: 즐겨찾기 예외처리 #253
  src/main/java/com/ncp/moeego/pro/service/ProServiceImpl.java
Labels: ref
